### ISSUE TITLE
Issue hardware and build Jenkins 2 instance for OBO

### ISSUE THREAD

**Issue by kltm** [berkeleybop/berkeleybop#1]
build.obolibrary.org jenkins 2 instance for obo
starting with build-mp-edit
talked to @cmungall , use one of our machines, at least 16GB
let's see what we got

**Comment by kltm** [comment]
In order of preference:
* dicer (down, was spotty in the past, can maybe make amends)
* grater (down, unused, why?)
* slicer (old vm host; wipe/upgrade)
* satin (move from current tasks)

**Comment by cmungall** [comment]
thx. Btw you can use the OBO tracker for this

**Comment by kltm** [comment]
Fair enough, but technically BBOP-only software and hardware (although the running Jenkins and such will be completely OBO).

**Comment by kltm** [comment]
Remember that we need the firewall down for the machine before attempting let's encrypt. A note to LBL should be enough for them to bring it down until we can get the cert.
