### ISSUE TITLE
Move code.berkeleybop.org to S3/CF

### ISSUE THREAD

**Issue by kltm** [berkeleybop/berkeleybop#3]
This is the current plan for getting rid of the (now considered) hideous code.berkeleybop.org

- [x] create job to write index files (reuse GO pipeline indexer)
- [x] upload to S3
- [x] DNS change <strike>(CloudFront distribution)</strike> (clever S3 bucket)
- [x] test
- [x] move fs tree (~500MB) to common space for "archive" <strike>(on jenkins NFS, user space?)</strike> (zenodo)
- [x] decommission knife, etc.

@nathandunn I seem to recall that you made use of this at some point?
@balhoff / @goodb How does this sound to you?

**Comment by balhoff** [comment]
> create job to write index files (reuse GO pipeline indexer)

What does this mean?

**Comment by kltm** [comment]
S3 does not, strictly speaking, delivery websites, like Apache does. To get something that is browsable in some way, one must index it “manually”.

**Comment by kltm** [comment]
@balhoff @goodb @dougli1sqrd
Is there a way to test maven builds with http://code-berkeleybop-org.s3-website-us-east-1.amazonaws.com instead of http://code.berkeleybop.org ? It would be good to test this before switching the DNS record from knife.lbl.gov.

**Comment by goodb** [comment]
@kltm for minerva, it now does not make use of code.berkeleybop.org at all.  If you wanted to run a test, we could change the reference in the pom in an older version of the code.  It would be in a repositories xml blob in the root pom.xml

**Comment by kltm** [comment]
I believe the repo is still used for a few other things, as well as reproducibility (it's bad to blink off the repo if we can avoid it).
A test of some kind would be good, as we to not have fast control of the DNS record in this case. Otherwise, we can wait until after the Thanksgiving break and just go for it.
@dougli1sqrd mentioned that he might try a test earlier on.

**Comment by kltm** [comment]
I've traveled back in time in minerva's repo (ab70654), changed `code.berkeleybop.org` to `code-berkeleybop-org.s3-website-us-east-1.amazonaws.com` and successfully built (./build-cli.sh), noting lines in the build like "Downloading: http://code-berkeleybop-org.s3-website-us-east-1.amazonaws.com/maven/snapshot-repository/org/bbop/OWLTools-Annotation/0.3.0-SNAPSHOT/maven-metadata.xml".
Would any of you consider this to be sufficiently tested to try switching the DNS?
@dougli1sqrd  @goodb @balhoff

**Comment by dougli1sqrd** [comment]
So in the pom, you changed the repository in the pom like we discussed, and everything worked out? That seems like a good test to me.

**Comment by goodb** [comment]
Whats the worst that could happen?

**Comment by kltm** [comment]
Well, people who still have OWLTools in their poms won’t be able to build their software and be confused as to who to contact to fix it. Then I’d feel bad. 
That said, I think it’s been reasonably tested at this point and I’ll go ahead tomorrow-ish.

**Comment by kltm** [comment]
As part of current power outage, I've requested LBL change the CNAME to the endpoint code-berkeleybop-org.s3-website-us-east-1.amazonaws.com.
The reason I think we didn't move forward before is that we have no easy way to test an roll back as it's a DNS record managed by LBL, meaning that there is always a lag. Now that the power is off, there is little reason not to try now as users are already being effected.
@balhoff

**Comment by kltm** [comment]
Due to DNS issues and LBL, I'm going ahead and trying this with S3-only, not CF. This means that there will be occasional rare outages, but probably pretty good.
I'm now using the bucket `code.berkeleybop.org` instead of `code-berkelybop-org`, as that's needed for the CNAME to work in this case with S3.

This should now be ready for general testing: @balhoff @goodb @nathandunn

**Comment by kltm** [comment]
@nathandunn I see you have a :hooray: there. What is your use case again? You are even there on the original ticket, but I don't have a record...

**Comment by balhoff** [comment]
@kltm it's working for me!

**Comment by kltm** [comment]
Awesome~!

**Comment by nathandunn** [comment]
@kltm   I can't remember the original use-case. 

I feel like when we move things to S3 it somehow lowers your long-term work load (and otherwise unnecessary trips up the hill). 

Also working for me!

**Comment by kltm** [comment]
The next item there is "move fs tree (~500MB) to common space for "archive" (on jenkins NFS, user space?)". At this point, it seems silly to have it on local hardware as a "backup" as that is already one of our failure points. I'm going to drop it into Zenodo instead, so we can find it there in case AWS/S3 decides to pack up and we need to re-host.

**Comment by kltm** [comment]
Archive available here:
https://doi.org/10.5281/zenodo.3891930

**Comment by kltm** [comment]
While knife is "up", as well as its host, I have marked them as "TBD" in assets. I believe we're done here except for cleanup that will naturally occur.
